# Generated by Django 4.2.5 on 2025-05-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CAN_BO_DOAN', 'Cán bộ đoàn'), ('ADMIN', 'Admin'), ('DOAN_VIEN', 'Đoàn viên')], default='DOAN_VIEN', max_length=20),
        ),
    ]
