# Generated by Django 4.2.5 on 2025-05-03 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='member_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MemberStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_activities', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('attendance_rate', models.IntegerField(default=0)),
                ('rank', models.CharField(default='Chưa xếp hạng', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_statistics',
            },
        ),
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_activities', to='core.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MemberAchievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_achievements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UnionFeeStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(choices=[(1, 'Quý 1'), (2, 'Quý 2'), (3, 'Quý 3'), (4, 'Quý 4')])),
                ('paid', models.BooleanField(default=False)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='union_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'union_fee_status',
                'ordering': ['-year', 'quarter'],
                'unique_together': {('user', 'year', 'quarter')},
            },
        ),
    ]
