# Generated by Django 4.2.5 on 2025-05-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_avatar_user_department_user_member_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='publish_status',
            field=models.CharField(choices=[('Draft', 'Bản nháp'), ('Published', 'Đã xuất bản')], default='Draft', max_length=20),
        ),
    ]
