# Generated by Django 4.2.5 on 2025-05-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activity_activity_type_activity_publish_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='publish_status',
        ),
        migrations.AddField(
            model_name='activity',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Học tập', 'Học tập'), ('Tình nguyện', 'Tình nguyện'), ('Văn hóa', 'Văn hóa'), ('Thể thao', 'Thể thao'), ('Khác', 'Khác')], default='Khác', max_length=50),
        ),
    ]
