# Generated by Django 4.2.5 on 2025-05-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityregistration',
            name='attendance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ duyệt'), ('Approved', 'Đã duyệt'), ('Rejected', 'Từ chối'), ('Attended', 'Đã tham gia'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20),
        ),
    ]
