# Generated by Django 4.2.5 on 2025-05-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activityregistration_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityregistration',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='dietary_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='reason',
            field=models.TextField(blank=True, help_text='Lý do tham gia hoạt động', null=True),
        ),
    ]
